language: java

jdk:
  - openjdk17

# Need a full git clone in order to be able to tag the release
git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout $TRAVIS_BRANCH
  - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
  - gpg --fast-import .travis/gpg.asc

env:
  global:
    # Environment variables referenced in .travis/maven-settings.xml. To encrypt and escape values correctly, run the following
    # command and enter ENV_VAR=value when prompted:
    # read -r && travis encrypt "$(printf %q "$REPLY")"
    - secure: bdWhbkkcVoMJMbS1WR4DVklTeD5bTJUQZJuTqlHfH7Gs4Jf3fsuOJ+DCkzJEnDM8e9k663QIKghitRFtn1DTKyafB8ql1eQj44ZaUPaP5GbReexpuQqt+lsEUgfwFENUosN6S679nOZ31Xjkmuf4AGDtfPkTh3qjZiPbC9MMzgwba15/9erXA7GBNhISseQWb4srC3APy4yLBUYFHxiV/pqRjP4ZSTwnhNsyaAi2HfYo5NpHP9llILnsSgShBRhtYpPzG0sn7Dw3jbYYQmsu9bDZmYKQTDycnuxRShpnHMBPV+zpJbX5EIkKlARGHbioND5i8JIokZ1nuqpJ1twFR227JpBzuM9LM7+L/bD9I5hYcmL2ltmSMg8AcBbknfNGaGP+kk/6BZ3vK1Uu1ZSYReLNyz4iDXI+DDVnJ/L3QUnn+e7G6vnACiAsN9VJrQE88/LzrG/wMaKre0o1KqniKnQ4qH2xNKHGYjubiauEYykNY+BICPVb8Td945FbJ2a+7Gsc6kkKot4Vuhe1Mk1uSo1H/tlk+uQo+Lki6g/WvslwNi37rVHslrw+kMX+n5BHQyUzubfgzbSuWmZDiV6d9Z66Lr1nDpkXmuFLTWlqYFj5jwqmZMS/ms5rOfYU79ISMW02bUoFPxc298KSalPzaXeHZv5rvdGGGeQ/mF+0RDQ=
    - secure: TC3/QEWEs5ufSn0hWnnPV5TGXNpBks6Oco/k3EEyTxrszcJEg3gV2WvStbIaQll2AWb+uGUJ7R1eLE8/g+a06+II9uVLFb42B56nyy+n0HtU0YeI9bAg4DRd6j5lRdToRHPi4NQyV2dEeM8W9CAk8Oj1WZp4lVWQ2ZHuy7yaZd8JYlcacZF70XtrD+R61y/6Emb9E2P2kcMuzkePCY3SYVlDReLv/6Mon1oIRS2NmD/2vZahjC/Ki85/KrwKCmPFhqV0q/6NGWYa/lYktuqDnuOJTP9tliom2KwwgyL0bB9UR/Yq3AoF1KUqU2xpPDgmYwfy1ufwrr7+oyN9S0jLQLkiIGGxIJqVEqXEljbIclFRmFdPlnykM3sQL/uiyEzidMpg5Xz2NRY4BrKCwPTagQ58AtS4UkXeK+rB3x6G5pKM1uPXJyIN3sBiTj3Vz3Pa748JZ6ot8hv05CR3CDgDP72FXsR/KMGv5dCuArTBAOT+wF/0RbPF/6ptazmOqVJ1HUvB5cSmE52hxZNElo1zqLQlc2w98BUe/d7EZXzpn9cKDlWqxrm8+GChNGf1YtEYkI4wFL2R/mGkv9MgyHaewVDPaosRUhxBIqwOIFox6U+rMfDZMsP8xCUcns+3mno3Gt8kVPh05MyUcOTVLGSeYoZA4B6tZWdokeAKu9X5f3c=
    - secure: U+6ajXnLPyMGjVkDR2L7WxmmTJb9FcE7veX07yoPAYB/UKdTg57+8sxsAKgPZbV90kxtUYXKSSum3dl5VeG5GlarlquD2DxdfnDUzh/4UufWVw/ZwFMOX8/OLxnJ59UBMYNoj+yAkqxx6Y/bfBjtAAgDjaVYbGrJUvGvu+YfnKUeo5h9Ej3seymdmbS5DITjjqPNnjE5BemoDQ9JMR12q7nH02ONgyetjbT3vsvJtnXe6tOS3OisU1LKkq0g8ESG3mhTLfEr2ntu+sHk1oU7/E3NfjBV+aWMTv8GM6Ma329kXAhZaKYraJjaFv1cplVKiloZJCD6CJvhdlrRsbzvF1yVEEqpzzBk1hlkc/B4dw4qgWeKHl9T7zISCDZB3RZiyKH+NPbV0AUHocKnGSKvPFw+kZjXIlMGPEce5wWqqXwpprz8wRNv5r2BlJ+fDxGMojPFYpRL+EOMNLCcYoJuz6lQlcrBGnULzzfSvZQaRmQJPb8KYv7j+TSy+pQJr7rJcStawpPCqpoFA5QFkAFSsflHQDSOQ/QVE3v7GTtuKYcinLsyWAx7yxF+rafBI/++ZVtRNBpEn60m+5dXeRBTU+UBEBkm02UZ4hig2b2FyYEIWarFji3mP5YtivJSY4hjfvJtB0KwkJza8AM6iUyaIH+fPHsS16c76JyuuTwnLGM=
    - secure: yxVa7/1zXQdVWekfiPjIQv9Bs19Wiz1g8WqBOhkDiHwrfM0BZ4UWSTP/SuXxlb60V3VaeG9uUKIfXULleOcEZ4vp+eTcUeVSnmegEf+HATQxicZyWA7sWd3B8tV7gS0y3T4BHBmEbvDP0IHPSzVT/54Uf0q+PUtrOyOZIwYIxxLbC4hFE85tneQrycUggqPx5mAdB6DFwDCgvuJz1r6yyHYGPT1bvuCfuLZrnmHa0y+9fC6Apt8V2hnjL3f9sLwq1lEUbrSj3N5WTKDeU8pC6DAgsnkRHIfxZAwabdCWivcd6F7M/rIsIqhb4DyXOMpPFKlmgVzCfsPFuAEDTIQTQuVzayIcJomVmrCeILE+xAyqNLOYLFTWOGmbJqUPPquYvsltI9iZFPgc5Lz3pTv9NYqaDIuTfw/8hH18/9CUesAGcw8igCKYEQVFwlp78g42y7bvbOG/7qdN37H8jTD9tBqSnF13Bw3CK1ta4OaTnSUtXy5W11zIKZ6UW7AD/mzlZg3yAN2s8roAzH9YHZYsZr6V3suDq4tFrTcfKjHp1j6sSIsi0V+GNCnZAE3dHSbU0a2sZ4tzPrGfsMrjnjt0a2Qn/j+eQ62oK97fV/5RgkTDpl6NL7VvBk2UCM4ync0thw6kQC3RGYjjq9tNmMWpk2KR+1+jcWwNni2I6m3snLQ=
    - secure: WYACISJtScM7HiqBdftP53iCwlYXlLpZ/Y/QslqSqvjnfo1rGtrBXoVKMSeJFP7TRcsAfgAz2KzdWtnjv2ZQlDnjmtVSNxgJWz1hEIhzzIDXbiN+p7b2RzHzMueB1+ZYLUB7Av/aTqIzkmEWHTOczVuW0ET0raMUPp0zG2EbnrtNRxzoZeWpnP68uRnol5XpcA2WVKyK7TOjykBBBtRIT0IGMOhQXIlylPLIeHmaRKl8Vdlf8u6QI567AP37l6ErZxUq6PbN08pigJJ7tptiameVqqV4YahRVyW4wURZVbP3QXmkFeJlbYyybF457QCVdh/tiz1KbXkm9drCLcjYUulRjz10YhB/zH44Xu/yCWUINO9UB6UTqZhynLTcwqaU9btw9XNY23FToX3vkEiN08Z+CpFCy2TxU6OeqWkfV4nrqSbryQ2oH9/my5mu1erbWX8+UjfRp88eVLLAm0dGhbmS6eug5il3m9lu0IvS6mgQT75w8ErV1HQ4MIa6nWZnOZH+wvphbA07g5U/VdsI6odYcAePNe9+b4bcofM86+hHLzQ/NirIQf0ldik++72ALigeCQ9usSDKZh0O0W6IkNm7H8oSFqaJL0iUbLdmSiqtfhhF2/Cdpudso0teofXzTfVm3baymuYZCUIFmF5EY1iHrIId6hLM/th/JqU0How=

script:
  - mvn clean install -B
  - mvn org.pitest:pitest-maven:mutationCoverage -B

before_deploy:
  # Set tag to be used by releases provider
  - export TRAVIS_TAG=$POM_VERSION

deploy:
  # For any checkin to main branch, create a final version, tag it and push the artifacts to Sonatype
  - provider: script
    skip_cleanup: true
    script:
      mvn --settings .travis/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
    on:
      branch: main

  # Releases config copied from https://docs.travis-ci.com/user/deployment/releases/ and secure key generated by following
  # https://stackoverflow.com/questions/25302518/travis-ci-setup-releases-with-github-token#answer-57032190
  - provider: releases
    api_key:
      secure: xDrcEKR1ycnc3j6/Ichelv8bTMoH+3k0PrcBvDsj8eXE+rOdMd4nz3RcFTw/YMa/cOe5lBhLawtO82Uw7486E0UlLBqkuf5hZJW9xz0+zd1Z2hFuFpz0ThDhORJaOfUH463BgPAjIABKOmEEjJsUuzoDioGbjoHQjy1r+nPL3WTilhM1WwMBgpUSqzKeybOxo+muUAOt8DoK1VoYw0nqDIUp855TEQQFSjl2p5fmCidbodXGik915ouveseQ8bkqTPLjeHVID3qjsTBE1n8TvzK7ADbAdDaMRWXGxtWmKrtBEMA349gMZyLRxI7QkFt/TK0HRb6E0ABr0BaSzIKm2Jv1nK9/JOh5qHs7DzlBEnVQGpYl10qNi82TyRVMLIcnXQMRNsRCQ7AmwkMj7vfQWvZEScP5BBRpToQy8ebbxuvPU/w7THGR4tmn2gCzJ5eD5T37c6rsEVTx3ILgZizKfmmp9WstIRJQv+YTaMQvmYDIMBa6EFQ5wdWc0fI4VT1j7WnYDKoBgSmsCK3vktw5XEXCBfrOIXdbD6fNZlOY5GcGiinsYsi/xkNE0ntg1+UjSFkFlqg2YQxLQgx1Ha2z4EqIAqPX+kDnPaXWv2LIX4Rw994+wCJ5CV3ZNo8VI1DSJ2k8DWsO9cdr3jm70nkRYNNwySS6g/pn0VjE2ycszdw=
    file:
      - "spt-development-audit-spring-boot-autoconfigure/target/spt-development-audit-spring-boot-autoconfigure-${POM_VERSION}.jar"
      - "spt-development-audit-spring-boot-starter/target/spt-development-audit-spring-boot-starter-${POM_VERSION}.jar"
    skip_cleanup: true
    on:
      branch: main