name: spt-development-audit-spring-boot

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 22
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 22

      - name: Run Maven
        run: ./mvnw clean install -Pall-quality-gates -B

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up JDK 22
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 22
          
      - name: Determine version
        run: echo "POM_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')" >> $GITHUB_ENV

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Configure Git User for updating version
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Create release
        run: ./mvnw --settings .github/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GIT_HUB_USERNAME: ${{ secrets.GIT_HUB_USERNAME }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create GitHub release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.POM_VERSION }}
          artifacts: spt-development-audit-spring-boot-autoconfigure/target/spt-development-audit-spring-boot-autoconfigure-${{ env.POM_VERSION }}.jar,spt-development-audit-spring-boot-starter/target/spt-development-audit-spring-boot-starter-${{ env.POM_VERSION }}.jar
          artifactContentType: application/java-archive
          bodyFile: documentation/releases/release-${{ env.POM_VERSION }}.md